# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apache:
      repo: "puppetlabs/apache"
      ref: "9.0.1"
    archive:
      repo: "puppet/archive"
      ref: "4.5.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "6.2.0"
    dhcp:
      repo: "puppet/dhcp"
      ref: "4.0.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.3.0"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
      ref: "3.1.1"
  repositories:
    nginx:
      repo: "https://github.com/aursu/puppet-nginx.git"
      ref: "tags/v1.1.1-rc0.5"
    openssh: "https://github.com/aursu/puppet-openssh.git"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      ref: "tags/1.0.7"
      puppet_version: ">= 6.0.0"
