# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apache:
      repo: "puppetlabs/apache"
      ref: "12.2.0"
    apt:
      repo: puppetlabs/apt
      ref: 9.4.0
    archive:
      repo: "puppet/archive"
      ref: "7.1.0"
    bsys:
      repo: aursu/bsys
      ref: 0.8.0
    concat:
      repo: "puppetlabs/concat"
      ref: "9.1.0"
    dhcp:
      repo: "puppet/dhcp"
      ref: "6.1.0"
    nginx:
      repo: "aursu/nginx"
      ref: "6.0.2"
    openssh:
      repo: "aursu/openssh"
      ref: "0.9.6"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "9.7.0"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
      ref: "6.1.0"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      ref: "2.1.0"
