# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apache:
      repo: "puppetlabs/apache"
      ref: "12.0.3"
    archive:
      repo: "puppet/archive"
      ref: "7.1.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "9.0.0"
    dhcp:
      repo: "puppet/dhcp"
      ref: "6.1.0"
    nginx:
      repo: "aursu/nginx"
      ref: "4.4.2"
    openssh:
      repo: "aursu/openssh"
      ref: "0.9.5"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "9.2.0"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
      ref: "6.1.0"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      ref: "2.1.0"
